// <auto-generated />
namespace Housing_RedBadgeMVC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class IsSafeTwo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsSafeTwo));
        
        string IMigrationMetadata.Id
        {
            get { return "202010090158426_IsSafeTwo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
